---
 - hosts: loadbalancer
   become: true
   gather_facts: false
   tasks:
     - name: verify nginx service
       command: service nginx status
     - name: verify nginx listening on 80
       wait_for: port=80 timeout=1

 - hosts: webserver
   become: true
   gather_facts: false
   tasks:
     - name: verify apache2 service
       command: service apache2 status

     - name: verify apache2 listening on 80
       wait_for: port=80 timeout=1

 - hosts: database
   become: true
   tasks:
      - name: verify mysql service
        command: service mysql status

      - name: verify mysql listening on 3306
        wait_for: host={{ ansible_eth0.ipv4.address }} port=3306 timeout=1

 - hosts: loadbalancer
   become: true
   gather_facts: false
   tasks:
       - name: verify end-to-end response
         uri: url=http://{{item}} return_content=yes
         with_items: groups.loadbalancer
         register: app_index

       - fail: msg="index failed to return content"
         when: "'Hello, from sunny' not in item.content"
         with_items: "{{app_index.results}}"

       - name: verify backend db response
         uri: url=http://{{item}}/db return_content=yes
         with_items: groups.loadbalancer
         register: app_db_result

       - fail: msg="db failed to return content"
         when: "'Database Connected' not in item.content"
         with_items: "{{app_db_result.results}}"


